name: 数据同步

on:
  schedule:
    - cron: '0 0 ? 1-12 1-2'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update
        run: |
          yarn
          GITHUB_TOKEN=${{secrets.TOKEN}} npm run update:data
